"""integrations: settings, linkedin, calendar, mail; inbox.notified_at

Revision ID: 0002
Revises: 0001
"""

from alembic import op
import sqlalchemy as sa

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("start_min", sa.Integer(), nullable=False),
        sa.Column("end_min", sa.Integer(), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid", "day"),
    )
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calendar_events_day"), ["day"], unique=False
        )

    op.create_table(
        "integration_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "linkedin_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("about", sa.Text(), nullable=False),
        sa.Column("experience", sa.Text(), nullable=False),
        sa.Column("skills_text", sa.Text(), nullable=False),
        sa.Column("activity_posts_90d", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mail_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(length=300), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("sender_domain", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("injection_flags", sa.JSON(), nullable=False),
        sa.Column("handled", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    with op.batch_alter_table("mail_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mail_items_day"), ["day"], unique=False)

    with op.batch_alter_table("inbox_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True)
        )

    with op.batch_alter_table("recovery", schema=None) as batch_op:
        batch_op.alter_column("subjective", nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recovery", schema=None) as batch_op:
        batch_op.alter_column("subjective", nullable=False)

    with op.batch_alter_table("inbox_items", schema=None) as batch_op:
        batch_op.drop_column("notified_at")

    with op.batch_alter_table("mail_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mail_items_day"))

    op.drop_table("mail_items")
    op.drop_table("linkedin_profile")
    op.drop_table("integration_settings")
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendar_events_day"))

    op.drop_table("calendar_events")
    # ### end Alembic commands ###
